# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1294, 847)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"    background:rgb(30, 30, 30);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setStyleSheet("QFrame{\n"
"      color:rgb(60, 60, 60);\n"
"      background:rgb(30,30,30);\n"
"      border-top:1px solid darkGray;\n"
"      border-bottom:1px solid darkGray;\n"
"      border-right:1px solid darkGray;\n"
"      border-left:1px solid darkGray;\n"
"      border-top-right-radius:5px;\n"
"      border-bottom-right-radius:5px; \n"
"      border-top-left-radius:5px;\n"
"      border-bottom-left-radius:5px; \n"
"}\n"
"QLabel{\n"
"    border:none;\n"
"    color:white;\n"
"    font-size:16px;\n"
"    font-weight:700;\n"
"    font-family: \"微软雅黑\";\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    background:rgb(50,50,50); ;\n"
"    border-radius:3px;\n"
"    font-size:15px;\n"
"    font-weight:700;\n"
"    font-family: \"微软雅黑\";\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(42,105,192);\n"
"    font-size:15px;\n"
"    font-weight:700;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.viewManual = QtWidgets.QPushButton(self.frame_4)
        self.viewManual.setObjectName("viewManual")
        self.verticalLayout_2.addWidget(self.viewManual)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame = QtWidgets.QFrame(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("QFrame#frame{\n"
"      color:rgb(60, 60, 60);\n"
"      background:rgb(30,30,30);\n"
"      border-top:1px solid darkGray;\n"
"      border-bottom:1px solid darkGray;\n"
"      border-right:1px solid darkGray;\n"
"      border-left:1px solid darkGray;\n"
"      border-top-right-radius:5px;\n"
"      border-bottom-right-radius:5px; \n"
"      border-top-left-radius:5px;\n"
"      border-bottom-left-radius:5px; \n"
"}\n"
"\n"
"QComboBox{\n"
"    font-size:12px;\n"
"    font-weight:700;\n"
"    font-family: \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton{\n"
"    color:white;\n"
"    background:rgb(50,50,50); ;\n"
"    border-radius:3px;\n"
"    font-size:15px;\n"
"    font-weight:700;\n"
"    font-family: \"微软雅黑\";\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(42,105,192);\n"
"    font-size:15px;\n"
"    font-weight:700;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.OpenorClose = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.OpenorClose.setFont(font)
        self.OpenorClose.setObjectName("OpenorClose")
        self.gridLayout.addWidget(self.OpenorClose, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.baudRate = QtWidgets.QComboBox(self.frame)
        self.baudRate.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.baudRate.setFrame(True)
        self.baudRate.setObjectName("baudRate")
        self.baudRate.addItem("")
        self.baudRate.addItem("")
        self.baudRate.addItem("")
        self.gridLayout.addWidget(self.baudRate, 2, 1, 1, 1)
        self.portId = QtWidgets.QComboBox(self.frame)
        self.portId.setObjectName("portId")
        self.gridLayout.addWidget(self.portId, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 4)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("QFrame#frame{\n"
"      color:rgb(60, 60, 60);\n"
"      background:rgb(30,30,30);\n"
"      border-top:1px solid darkGray;\n"
"      border-bottom:1px solid darkGray;\n"
"      border-right:1px solid darkGray;\n"
"      border-left:1px solid darkGray;\n"
"      border-top-right-radius:5px;\n"
"      border-bottom-right-radius:5px; \n"
"      border-top-left-radius:5px;\n"
"      border-bottom-left-radius:5px; \n"
"}\n"
"\n"
"QLineEdit{\n"
"    font-size:12px;\n"
"    font-weight:700;\n"
"    font-family: \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton{\n"
"    color:white;\n"
"    background:rgb(50,50,50); ;\n"
"    border-radius:3px;\n"
"    font-size:15px;\n"
"    font-weight:700;\n"
"    font-family: \"微软雅黑\";\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(42,105,192);\n"
"    font-size:15px;\n"
"    font-weight:700;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.data_save = QtWidgets.QPushButton(self.frame_2)
        self.data_save.setObjectName("data_save")
        self.gridLayout_4.addWidget(self.data_save, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    background:rgb(50,50,50); ;\n"
"    border-radius:3px;\n"
"    font-size:15px;\n"
"    font-weight:700;\n"
"    font-family: \"微软雅黑\";\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(42,105,192);\n"
"    font-size:15px;\n"
"    font-weight:700;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.frame_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(1)
        self.splitter.setObjectName("splitter")
        self.readDistance = QtWidgets.QPushButton(self.splitter)
        self.readDistance.setObjectName("readDistance")
        self.calibrate = QtWidgets.QPushButton(self.splitter)
        self.calibrate.setIconSize(QtCore.QSize(16, 16))
        self.calibrate.setAutoDefault(False)
        self.calibrate.setDefault(False)
        self.calibrate.setFlat(False)
        self.calibrate.setObjectName("calibrate")
        self.calculateDepth = QtWidgets.QPushButton(self.splitter)
        self.calculateDepth.setObjectName("calculateDepth")
        self.clearScreen = QtWidgets.QPushButton(self.splitter)
        self.clearScreen.setObjectName("clearScreen")
        self.quit = QtWidgets.QPushButton(self.splitter)
        self.quit.setObjectName("quit")
        self.verticalLayout_4.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    color:white;\n"
"    font-size:26px;\n"
"    font-weight:700;\n"
"    font-family: \"楷体\";\n"
"}\n"
"QWidget#customPlot{\n"
"    color:#232C51;\n"
"    background:rgb(47,48,48);\n"
"    border-top:1px solid darkGray;\n"
"    border-bottom:1px solid darkGray;\n"
"    border-right:1px solid darkGray;\n"
"    border-left:1px solid darkGray;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-right-radius:10px; \n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}\n"
"QTextEdit{\n"
"    color: white;\n"
"    font-family: \"JetBrains Mono\";\n"
"    background:rgb(75,75,75);\n"
"    border-top:1px solid darkGray;\n"
"    border-bottom:1px solid darkGray;\n"
"    border-right:1px solid darkGray;\n"
"    border-left:1px solid darkGray;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-right-radius:10px; \n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px; \n"
"}\n"
"QTextBrowser{\n"
"    color: white;\n"
"    font-size: 12px;\n"
"    font-family: \"JetBrains Mono\";\n"
"    background:rgb(75,75,75);\n"
"    border-top:1px solid darkGray;\n"
"    border-bottom:1px solid darkGray;\n"
"    border-right:1px solid darkGray;\n"
"    border-left:1px solid darkGray;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-right-radius:10px; \n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 3, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(-1)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.customPlot = QCustomPlot(self.widget_2)
        self.customPlot.setObjectName("customPlot")
        self.gridLayout_2.addWidget(self.customPlot, 1, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    color:white;\n"
"    font-size:15px;\n"
"    font-weight:700;\n"
"    font-family: \"微软雅黑\";\n"
"}")
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    color:white;\n"
"    font-size:15px;\n"
"    font-weight:700;\n"
"    font-family: \"微软雅黑\";\n"
"}")
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 1, 1, 1)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 6)
        self.gridLayout_2.setRowStretch(3, 3)
        self.horizontalLayout.addWidget(self.widget_2)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/Icons/gtk-help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon)
        self.actionHelp.setObjectName("actionHelp")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.viewManual.setText(_translate("MainWindow", "查看使用说明"))
        self.label_4.setText(_translate("MainWindow", "操作："))
        self.label_2.setText(_translate("MainWindow", "端口："))
        self.OpenorClose.setText(_translate("MainWindow", "打开串口"))
        self.label_3.setText(_translate("MainWindow", "波特率："))
        self.baudRate.setItemText(0, _translate("MainWindow", "4800"))
        self.baudRate.setItemText(1, _translate("MainWindow", "9600"))
        self.baudRate.setItemText(2, _translate("MainWindow", "115200"))
        self.data_save.setText(_translate("MainWindow", "保存文件"))
        self.readDistance.setText(_translate("MainWindow", "读取当前距离"))
        self.calibrate.setText(_translate("MainWindow", "校准基准面"))
        self.calculateDepth.setText(_translate("MainWindow", "测量深度值"))
        self.clearScreen.setText(_translate("MainWindow", "清空输出"))
        self.quit.setText(_translate("MainWindow", "退出程序"))
        self.label.setText(_translate("MainWindow", "激光测距图形化界面"))
        self.label_10.setText(_translate("MainWindow", "基准面距离"))
        self.label_11.setText(_translate("MainWindow", "深度值"))
        self.actionHelp.setText(_translate("MainWindow", "使用说明"))
        self.actionHelp.setShortcut(_translate("MainWindow", "Ctrl+H"))
from QCustomPlot_PyQt5 import QCustomPlot
